version: '2.1'
services:
  front:
    build: front
    restart: always
    ports:
      - 80:4000

  banner-service:
    build: banner-service
    restart: always
    ports:
      - 9090:9090

  account-service:
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
    build: account-service
    restart: always
    ports:
      - 6000:6000

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: password
    build: mongodb
    restart: always
