version: '2.1'
services:
  front:
    container_name: front
    build: front
    restart: always
    ports:
      - 80:4000
    networks:
      - test

  banner-service:
    container_name: banners
    build: banner-service
    restart: always
    ports:
      - 80:9090
    networks:
      - test

  account-service:
    container_name: accounts
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
    build: account-service
    restart: always
    ports:
      - 80:6000
    networks:
      - test

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: password
    build: mongodb
    restart: always
    
networks:
  test:
    name: test
